export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_RESETTING_LOGIN = 'USER_RESETTING_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST'
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS'
export const SUBSCRIBE_FAILED = 'SUBSCRIBE_FAILED'

export const UNSUBSCRIBE_REQUEST = 'UNSUBSCRIBE_REQUEST'
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS'
export const UNSUBSCRIBE_FAILED = 'UNSUBSCRIBE_FAILED'

export const GET_PLANS_REQUEST = 'GET_PLANS_REQUEST'
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS'
export const GET_PLANS_FAILED = 'GET_PLANS_FAILED'

export const SUBSCRIBTION_PLAN = 'SUBSCRIBTION_PLAN'

export const OPEN_TOAST = 'OPEN_TOAST'
export const OPEN_TOAST_RESET = 'OPEN_TOAST_RESET'
